import Head from 'next/head'
import PostCardsComponent from '../web/components/post-cards/post-cards.component'
import { observer } from 'mobx-react-lite'

const Home = observer(() => {

  return (
    <>
      <Head>
        <title>Post App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PostCardsComponent/>
      </main>
    </>
  )
})

export default Home;
